### PR TITLE
fixes #25

### LINKED ISSUE #25: Remove X button, place 'logout' in top-right list
Watching Johnny use the site, he accidentally logged out numerous times mistaking the X in the corner to mean a way to close an opened window within JoatU.  I would suggest we remove it entirely and replace it with a button that will send people to a random person's profile within their community. 

The logout option can be in the drop-down list on the top right.

### PR DESCRIPTION
**Pull request by TedEwanchyna**
Remove X button, place 'logout' in top-right list #25
I commented out the original logout button and added the logout to the menu.

### CODE REVIEW

**Comment by undergroundwebdesigns** [comment]
Looks like you also fixed #33 ?

**Comment by TedEwanchyna** [comment]
yes
i had two fixes, i made a git pull request on the first but i wasn't sure
if the second one went through, so i thought i would wait for the first to
clear and try the second request later. i guess the second also went
through?
i am concerned about the travis build error.

**Comment by undergroundwebdesigns** [comment]
Ya, the build error is weird, I'm not sure what's going on there. I don't think it's anything you've done, I think Travis is just being weird. I'm trying a build right now on an updated version of Ruby, with _might_ fix it? We'll see.

It looks like both your fixes made it into this one pull request, which isn't a problem. Do you mind removing the CSS code rather than just commenting it out, and the same with the logout link? If we ever need it, we'll go find it in git... I'd rather not have old stuff cluttering up the code ;).

**Comment by TedEwanchyna** [comment]
Alex,
I agree about deleting rather than commenting out code. I will do this but
I am still trying to develop my work flow with git.
So bear with me,
I am waiting for my pull requests to be accepted and then I could make the
deletions in another 2 pull requests.
I assume this is how to do it. Since I already made the request, I don't
know how to unmake it.
Or perhaps if you deny the request then I could resubmit?

I have set up the joattu code as a fork on my github account. I have my
remote named origin and your remote as upstream.

The first request I made on Friday went through OK. When I was waiting my
github said that I was 1 commit ahead.
When you accepted it then was up to date. I guess I am waiting to be up to
date again.

Once that occurs, I can look at changing this work flow. I have accepted
being part of joattu and have an account on slash.

Ted

**Comment by undergroundwebdesigns** [comment]
Hey Ted. I suggest you read up on Pull Requests (and Github in general). Here's a good place to start: https://help.github.com/categories/collaborating/.

Your basic setup is correct (forking the project). It sounds like you've been making your pull requests from the "develop" branch. Pull requests are tied to branches, so a better work-flow is to make a branch for each feature / or bug you want to work on, and make the pull request from there. Any further commits you make on a pull request's branch will update the pull request.

Since this pull request is tied to the develop branch, just go ahead and delete the commented code, commit, and push. It will update this pull request. 

While you're in there, also run these commands:
`git checkout develop` (you can probably skip this, if you're already on develop branch)
`git fetch upstream` (will update your local GIT so it knows about my latest changes)
`git merge upstream/develop` (this will merge my recent changes into your branch)
`git push` (this will push the changes to Github, and update the pull request).

Those steps should pull the changes I made yesterday to fix Travis CI into this pull request, which should get Travis CI passing. Once those things are done (Travis passing and the comments removed) I will merge this pull request.

**Pull request merged**
